---
- name: setup
  include_vars: "{{ ansible_user_shell | basename }}.yml"
  tags: always

#####=== configure ===#####

- block:
  - name: bash/zsh | configure | aliases
    blockinfile:
      dest: "{{ sensible_config_file }}"
      create: yes
      backup: no
      state: "{{ sensible_configure_state }}"
      marker: "{{ sensible_marker }}"
      block: "{{ sensible_config_block }}"
  when: ansible_user_shell | match(".*\/(bash|zsh)")
  tags:
    - bootstrap
    - bootstrap_sensible
    - configure
    - configure_sensible

- block:
  - name: fish | setup
    file: dest="{{ shell_data_dir }}/functions" state=directory

  - name: fish | configure | functions
    template:
      src: fish_function.j2
      dest: "{{ shell_data_dir }}/functions/{{ item.key }}.fish"
      force: yes
      backup: no
    with_dict: "{{ sensible_fish_functions }}"
  when: ansible_user_shell | match(".*\/(fish)")
  tags:
    - bootstrap
    - bootstrap_sensible
    - configure
    - configure_sensible
